### ISSUE TITLE
Error occurred in Anki v2.1.49

### ISSUE THREAD

**Issue by curious58** [firejake308/internal-references#2]
Hi! 

I've recently downloaded this add-on in my Anki v2.1.49 and I cannot create internal references because an Error message will pop-up. Please update for the newest version. This update would be so helpful in creating associations among cards.  

Thank you!

**Comment by PlotiniVox** [comment]
Hi!

I'm very very interested in this add-on, too. I didn't know that add-on before. After installing it on 2.1.49 and restarting I just don't know how/where to get the "create link" dialog, maybe it's not running at all?

Are there other powerful linking-add-ons for 2.1.49 you might recommend?

Thank you!

**Comment by curious58** [comment]
> Hi!
> 
> I'm very very interested in this add-on, too. I didn't know that add-on before. After installing it on 2.1.49 and restarting I just don't know how/where to get the "create link" dialog, maybe it's not running at all?
> 
> Are there other powerful linking-add-ons for 2.1.49 you might recommend?
> 
> Thank you!

The "create link" is actually in the form of an icon together with the other buttons (bold, italics, cloze, image occlusion, etc.) normally used in Anki. In mine, it's near the hyperlink buttons when making cards. Unfortunately, even if you can click the button and try to create a link, you'll encounter an error right after so the link cannot be created. Hope it gets fixed soon. 

There are 3 similar add-ons I've found. 

1. https://github.com/Arthur-Milchior/anki-link-to-open-browser/issues - sadly, it also has some compatibility issues with v2.1.49

2.  https://ankiweb.net/shared/info/1423933177 - Similar to the "internal references" add-on but you can't change the hyperlink name. Works fine with v2.1.49

3.  https://ankiweb.net/shared/info/1420819673
     --> I found this add-on today (recommended by the author of ^2nd add-on). It's actually quite useful but a bit hard to understand on how to use all of its functions (and not all of it is working as of the moment). However, the referencing option of this add-on is quite easy to use so if that's the only function you need, you can try this. I use the "copy card as in-line text (new)" to create a link for the card I want referenced. Then, I paste it to any field I like on the intended card (making sure to click the html editor button </> in the desired field first before pasting the link of the referenced card). You can rename the card you referenced in the link created after you paste it in the desired field. 

The only problem is that as of the moment, you cannot change the card's "anchor" description which will be displayed in the cards if you click a green button with a drop-down menu in the upper left-hand side of the cards you link. Well, you'll be fine even if you click it; nothing bad actually happens. But if you do, then you'll see the messy names of the linked cards and you might not like that. Apart from that, I love the concept of this add-on and it really has a lot of potential (especially for mind-mapping)!

**Comment by firejake308** [comment]
@curious58 Sorry, just now seeing this. Don't check my GitHub notifications often. If you're still interested in getting the problem fixed, would you mind sharing a screenshot or copy-paste of the error message?

**Comment by firejake308** [comment]
FYI, I finally got around to fixing this error, so it should work now
